"""initial

Revision ID: 6e4fc1d66d9e
Revises: 
Create Date: 2026-07-06 13:46:22.947507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4fc1d66d9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('farmer_phone', sa.String(), nullable=True),
    sa.Column('farmer_name', sa.String(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    
    if is_sqlite:
        with op.batch_alter_table('farmers') as batch_op:
            batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
    else:
        op.add_column('farmers', sa.Column('name', sa.String(), nullable=True))
        op.alter_column('pool_members', 'delivered',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True,
                   existing_server_default=sa.text("'PENDING'"))
        op.alter_column('pool_members', 'crop_quality_grade',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('pools', 'current_highest_bid',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True,
                   existing_server_default=sa.text('(0.0)'))
        op.alter_column('pools', 'winning_price',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    
    if is_sqlite:
        with op.batch_alter_table('farmers') as batch_op:
            batch_op.drop_column('name')
    else:
        op.alter_column('pools', 'winning_price',
                   existing_type=sa.Float(),
                   type_=sa.REAL(),
                   existing_nullable=True)
        op.alter_column('pools', 'current_highest_bid',
                   existing_type=sa.Float(),
                   type_=sa.REAL(),
                   existing_nullable=True,
                   existing_server_default=sa.text('(0.0)'))
        op.alter_column('pool_members', 'crop_quality_grade',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        op.alter_column('pool_members', 'delivered',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True,
                   existing_server_default=sa.text("'PENDING'"))
        op.drop_column('farmers', 'name')
        
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_table('allocations')
    # ### end Alembic commands ###

